# Generated by Django 4.2.6 on 2023-10-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='trust_level',
            field=models.CharField(default='new', max_length=255),
        ),
    ]
